project:
  type: book
  output-dir: docs
  resources: 
    # - Extras/styles.css
    # - Extras/copy-all-code.html
    - images/**


book:
  title: "Learn Pmetrics"
  author: "Michael Neely"
  date: "8/27/2025"
  chapters:
    - index.qmd
    - NPAG.qmd
    - examine.qmd
    - NPAG_cov.qmd
    - Compare.qmd
  #  - Simulate.qmd
  #  - PTA.qmd
  # Optional but useful in books:
  page-navigation: true
  # You can keep a top navbar in a book, too:
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    title: Sections
 
format:
  html:
    theme: cosmo
    css: Extras/styles.css
    toc: true
    toc-title: "On this page" 
    include-in-header: Extras/copy-all-code.html
    link-external-newwindow: true
    embed-resources: true
pdf:
    documentclass: scrreprt

execute:
  eval: false




